### PR TITLE
Moodle 4.0 fixes

### PR DESCRIPTION
**Pull request by sbourget**
Updates the module to work with Moodle 4.0.
Includes the following:

- Updates Module icon to support MOD_PURPOSE
- Add support for the New Question Bank APIs
- Updates all test to work with the new Navigation Layout
- Assorted codechecker fixes
- Bump version for new release

### CODE REVIEW

**Comment by sbourget** [comment]
@xow 
When you have a chance can you take a look at these changes.  The most noticeable change is the Icon (to fit with Moodle 4.0 UI changes, as the GIF didn't work well with the new rendering methods)

**Review by xow — APPROVED** [review]
Untested but looks all good

**Comment by xow** [comment]
Thanks again for contributing to this project now that I'm out of the loop in the moodle scene. Good stuff @sbourget

**Comment by sbourget** [comment]
I have one more fix coming as MDL-71696 just broke the plugin completely (It changed the DB schema of the question bank)  see https://moodle.org/mod/forum/discuss.php?d=432239#p1739651

Once I have that fixed, I'll merge everything.

**Comment by sbourget** [comment]
Updates the module to work with Moodle 4.0.
Includes the following:

    Updates Module icon to support MOD_PURPOSE
    Add support for the New Question Bank APIs
    Updates all test to work with the new Navigation Layout
    Change Font handling to address GDPR issues
    Assorted codechecker fixes

**Pull request merged**
