### PR TITLE
Activity completion support, improved scoring and logging

### PR DESCRIPTION
**Pull request by sbourget**
This patch resolves issue #22 and also partially implements #14.

It addresses the following:

    Adds tracking of user scores. Uses AJAX to write the scores to the database.
    Improves logging allowing teachers / admins to identify who has been using the module.
    Implements the callbacks for the outline and complete reports now that we have data that can be viewed on the reports.
    Implements course reset as now we have scores that can be cleared.
    Implements a page for teachers etc to view all student scores.
    Adds support for activity completion for both views and minimum score
    Adds unit tests for the events
    Fixes remaining travis issues (travis is now passing)

### CODE REVIEW

**Comment by sbourget** [comment]
Yes, I can work on implementing the Privacy API.
Is there anything else needed to allow this PR to be merged? (Other than fixing the version conflict?)

**Comment by sbourget** [comment]
@xow I just put together the GDPR support for this and updated the pull request as #43 (I had several conflicts attempting to update this PR, so it was easier to submit a new one.)

Let me know if there is anything else I can do to help move this issue along.

**Comment by xow** [comment]
Ah ok @sbourget should we close this one?

**Comment by sbourget** [comment]
Sure, lets close this one and hopefully finish this up in #43

**Pull request closed without merging**
