### PR TITLE
ADD composer.json

### PR DESCRIPTION
**Pull request by michaelmeneses**

### CODE REVIEW

**Comment by xow** [comment]
Thanks @michaelmeneses for working on this. What's the reasoning behind adding composer.json? Just curious! Thanks!

**Comment by michaelmeneses** [comment]
Hi @xow,

You can add **xow/moodle-mod_quizgame** as require in **MOODLE/composer.json**. Running the "composer update" command and COMPOSER (https://getcomposer.org/) will install the plugin in MOODLE/mod/.

See my project at https://github.com/michaelmeneses/moodle-composer. Here we use ROOT/MOODLE/. So you do not have to change anything in Moodle, not even MOODLE/composer.json.

I maintain a repository of plugins using SATIS (https://satis.middag.com.br/). I'm working to improve it.

Thank you.

**Comment by xow** [comment]
I hope this takes off! Merged

**Comment by michaelmeneses** [comment]
Thank you.

**Pull request merged**
